### PR TITLE
Updated Breakfast Prep Time

### PR DESCRIPTION
**Pull request by hezico**
## 🎯 Objective

_Note why you're making this change and any relevant issues_

## 🛠️ Changes made

_Note what you actual changes you're proposing_ 

## 👥 Who needs to review this Pull Request? 

_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Comment by hezico** [comment]
Hi, added the step for preparation

**Comment by hezico** [comment]
updating the time

**Comment by hezico** [comment]
Updating the pickles number

**Comment by matiaspba** [comment]
Ok, looks good!

**Comment by JamesJYWang** [comment]
Looks good!

**Pull request merged**
