### PR TITLE
Added Codemates to recipe .md

### PR DESCRIPTION
**Pull request by matiaspba**
## 🎯 Objective

Added Codemates to recipe

## 🛠️ Changes made

Added Codemates to recipe

## 👥 Who needs to review this Pull Request? 

@Arohrba5, @hezico, @matiaspba, @JamesJYWang, and @NgaLeVN

### CODE REVIEW

**Comment by NgaLeVN** [comment]
LGTM. Thank you

**Comment by JamesJYWang** [comment]
Looks good!

**Comment by Arohrba5** [comment]
Thanks for adding this!

**Comment by hezico** [comment]
Thanks @matiaspba!

**Pull request merged**
